#!/usr/bin/env python

import sys
import time

try:
    import pijuice
except ImportError as e:
    sys.stderr.write("copilot-battery: ERROR: can't load Python pijuice library.\n")
    sys.stderr.write("%s\n" % e)
    sys.exit(1)

try:
    pj = pijuice.PiJuice()

    while True:
        try:
            status = pj.status.GetStatus()['data']
            pwin = status['powerInput']
            pwin5 = status['powerInput5vIo']

            charge = pj.status.GetChargeLevel()
            error = charge['error']
            pct = charge['data']

            # produces lines like: "NO_ERROR 98 NOT_PRESENT PRESENT"
            sys.stdout.write("%s %d %s %s\n" % (error, pct, pwin, pwin5))

        except:
            sys.stdout.write("ERROR\n")

        sys.stdout.flush()
        time.sleep(1)

except KeyboardInterrupt:
    raise SystemExit(0)
