#!/bin/sh

cat <<EOF
NO_ERROR 98 NOT_PRESENT PRESENT
NO_ERROR 100 NOT_PRESENT PRESENT
NO_ERROR 99 NOT_PRESENT PRESENT
NO_ERROR 99 NOT_PRESENT PRESENT
NO_ERROR 98 NOT_PRESENT PRESENT
NO_ERROR 74 NOT_PRESENT PRESENT
NO_ERROR 73 NOT_PRESENT PRESENT
NO_ERROR 70 NOT_PRESENT PRESENT
NO_ERROR 65 NOT_PRESENT PRESENT
NO_ERROR 63 NOT_PRESENT PRESENT
NO_ERROR 64 NOT_PRESENT PRESENT
NO_ERROR 63 NOT_PRESENT PRESENT
NO_ERROR 63 NOT_PRESENT PRESENT
NO_ERROR 63 NOT_PRESENT PRESENT
NO_ERROR 63 NOT_PRESENT PRESENT
NO_ERROR 63 NOT_PRESENT PRESENT
NO_ERROR 63 NOT_PRESENT PRESENT
NO_ERROR 63 NOT_PRESENT PRESENT
NO_ERROR 63 NOT_PRESENT PRESENT
NO_ERROR 63 NOT_PRESENT PRESENT
NO_ERROR 56 NOT_PRESENT PRESENT
NO_ERROR 42 NOT_PRESENT PRESENT
EOF
